/*
** EPITECH PROJECT, 2024
** arcade
** File description:
** event
*/

#include "Sfml.hpp"

namespace arcade {
    namespace sfml {
        arcade::event::keys Sfml::getKey(sf::Keyboard::Key key) {
            switch (key) {
                case sf::Keyboard::A:
                    return arcade::event::keys::A;
                case sf::Keyboard::B:
                    return arcade::event::keys::B;
                case sf::Keyboard::C:
                    return arcade::event::keys::C;
                case sf::Keyboard::D:
                    return arcade::event::keys::D;
                case sf::Keyboard::E:
                    return arcade::event::keys::E;
                case sf::Keyboard::F:
                    return arcade::event::keys::F;
                case sf::Keyboard::G:
                    return arcade::event::keys::G;
                case sf::Keyboard::H:
                    return arcade::event::keys::H;
                case sf::Keyboard::I:
                    return arcade::event::keys::I;
                case sf::Keyboard::J:
                    return arcade::event::keys::J;
                case sf::Keyboard::K:
                    return arcade::event::keys::K;
                case sf::Keyboard::L:
                    return arcade::event::keys::L;
                case sf::Keyboard::M:
                    return arcade::event::keys::M;
                case sf::Keyboard::N:
                    return arcade::event::keys::N;
                case sf::Keyboard::O:
                    return arcade::event::keys::O;
                case sf::Keyboard::P:
                    return arcade::event::keys::P;
                case sf::Keyboard::Q:
                    return arcade::event::keys::Q;
                case sf::Keyboard::R:
                    return arcade::event::keys::R;
                case sf::Keyboard::S:
                    return arcade::event::keys::S;
                case sf::Keyboard::T:
                    return arcade::event::keys::T;
                case sf::Keyboard::U:
                    return arcade::event::keys::U;
                case sf::Keyboard::V:
                    return arcade::event::keys::V;
                case sf::Keyboard::W:
                    return arcade::event::keys::W;
                case sf::Keyboard::X:
                    return arcade::event::keys::X;
                case sf::Keyboard::Y:
                    return arcade::event::keys::Y;
                case sf::Keyboard::Z:
                    return arcade::event::keys::Z;
                case sf::Keyboard::Num0:
                    return arcade::event::keys::NUM0;
                case sf::Keyboard::Num1:
                    return arcade::event::keys::NUM1;
                case sf::Keyboard::Num2:
                    return arcade::event::keys::NUM2;
                case sf::Keyboard::Num3:
                    return arcade::event::keys::NUM3;
                case sf::Keyboard::Num4:
                    return arcade::event::keys::NUM4;
                case sf::Keyboard::Num5:
                    return arcade::event::keys::NUM5;
                case sf::Keyboard::Num6:
                    return arcade::event::keys::NUM6;
                case sf::Keyboard::Num7:
                    return arcade::event::keys::NUM7;
                case sf::Keyboard::Num8:
                    return arcade::event::keys::NUM8;
                case sf::Keyboard::Num9:
                    return arcade::event::keys::NUM9;
                case sf::Keyboard::Escape:
                    return arcade::event::keys::ESCAPE;
                case sf::Keyboard::LControl:
                    return arcade::event::keys::LCONTROL;
                case sf::Keyboard::LShift:
                    return arcade::event::keys::LSHIFT;
                case sf::Keyboard::LAlt:
                    return arcade::event::keys::LALT;
                case sf::Keyboard::LSystem:
                    return arcade::event::keys::LSYSTEM;
                case sf::Keyboard::RControl:
                    return arcade::event::keys::RCONTROL;
                case sf::Keyboard::RShift:
                    return arcade::event::keys::RSHIFT;
                case sf::Keyboard::RAlt:
                    return arcade::event::keys::RALT;
                case sf::Keyboard::RSystem:
                    return arcade::event::keys::RSYSTEM;
                case sf::Keyboard::Menu:
                    return arcade::event::keys::MENU;
                case sf::Keyboard::LBracket:
                    return arcade::event::keys::LBRACKET;
                case sf::Keyboard::RBracket:
                    return arcade::event::keys::RBRACKET;
                case sf::Keyboard::SemiColon:
                    return arcade::event::keys::SEMICOLON;
                case sf::Keyboard::Comma:
                    return arcade::event::keys::COMMA;
                case sf::Keyboard::Period:
                    return arcade::event::keys::PERIOD;
                case sf::Keyboard::Quote:
                    return arcade::event::keys::QUOTE;
                case sf::Keyboard::Slash:
                    return arcade::event::keys::SLASH;
                case sf::Keyboard::BackSlash:
                    return arcade::event::keys::BACKSLASH;
                case sf::Keyboard::Tilde:
                    return arcade::event::keys::TILDE;
                case sf::Keyboard::Equal:
                    return arcade::event::keys::EQUAL;
                case sf::Keyboard::Dash:
                    return arcade::event::keys::DASH;
                case sf::Keyboard::Space:
                    return arcade::event::keys::SPACE;
                case sf::Keyboard::Return:
                    return arcade::event::keys::RETURN;
                case sf::Keyboard::BackSpace:
                    return arcade::event::keys::BACKSPACE;
                case sf::Keyboard::Tab:
                    return arcade::event::keys::TAB;
                case sf::Keyboard::PageUp:
                    return arcade::event::keys::PAGEUP;
                case sf::Keyboard::PageDown:
                    return arcade::event::keys::PAGEDOWN;
                case sf::Keyboard::End:
                    return arcade::event::keys::END;
                case sf::Keyboard::Home:
                    return arcade::event::keys::HOME;
                case sf::Keyboard::Insert:
                    return arcade::event::keys::INSERT;
                case sf::Keyboard::Delete:
                    return arcade::event::keys::DELETE;
                case sf::Keyboard::Add:
                    return arcade::event::keys::ADD;
                case sf::Keyboard::Subtract:
                    return arcade::event::keys::SUBTRACT;
                case sf::Keyboard::Multiply:
                    return arcade::event::keys::MULTIPLY;
                case sf::Keyboard::Divide:
                    return arcade::event::keys::DIVIDE;
                case sf::Keyboard::Left:
                    return arcade::event::keys::LEFT;
                case sf::Keyboard::Right:
                    return arcade::event::keys::RIGHT;
                case sf::Keyboard::Up:
                    return arcade::event::keys::UP;
                case sf::Keyboard::Down:
                    return arcade::event::keys::DOWN;
                case sf::Keyboard::Numpad0:
                    return arcade::event::keys::NUMPAD0;
                case sf::Keyboard::Numpad1:
                    return arcade::event::keys::NUMPAD1;
                case sf::Keyboard::Numpad2:
                    return arcade::event::keys::NUMPAD2;
                case sf::Keyboard::Numpad3:
                    return arcade::event::keys::NUMPAD3;
                case sf::Keyboard::Numpad4:
                    return arcade::event::keys::NUMPAD4;
                case sf::Keyboard::Numpad5:
                    return arcade::event::keys::NUMPAD5;
                case sf::Keyboard::Numpad6:
                    return arcade::event::keys::NUMPAD6;
                case sf::Keyboard::Numpad7:
                    return arcade::event::keys::NUMPAD7;
                case sf::Keyboard::Numpad8:
                    return arcade::event::keys::NUMPAD8;
                case sf::Keyboard::Numpad9:
                    return arcade::event::keys::NUMPAD9;
                case sf::Keyboard::F1:
                    return arcade::event::keys::F1;
                case sf::Keyboard::F2:
                    return arcade::event::keys::F2;
                case sf::Keyboard::F3:
                    return arcade::event::keys::F3;
                case sf::Keyboard::F4:
                    return arcade::event::keys::F4;
                case sf::Keyboard::F5:
                    return arcade::event::keys::F5;
                case sf::Keyboard::F6:
                    return arcade::event::keys::F6;
                case sf::Keyboard::F7:
                    return arcade::event::keys::F7;
                case sf::Keyboard::F8:
                    return arcade::event::keys::F8;
                case sf::Keyboard::F9:
                    return arcade::event::keys::F9;
                case sf::Keyboard::F10:
                    return arcade::event::keys::F10;
                case sf::Keyboard::F11:
                    return arcade::event::keys::F11;
                case sf::Keyboard::F12:
                    return arcade::event::keys::F12;
                case sf::Keyboard::F13:
                    return arcade::event::keys::F13;
                case sf::Keyboard::F14:
                    return arcade::event::keys::F14;
                case sf::Keyboard::F15:
                    return arcade::event::keys::F15;
                case sf::Keyboard::Pause:
                    return arcade::event::keys::PAUSE;
                default:
                    return arcade::event::keys::UNKNOWN;
            }
        }
    }
}